# Generated by Django 5.2.4 on 2025-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('paper_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('paper_file', models.FileField(upload_to='papers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
